In [27]:
import numpy as np

Service = [-2,-1,2,1]
Qualite = [3,1,-1,3]
Prix = [-1,0,-1,2]
# Compute the means
mx = np.mean(Service)
my = np.mean(Qualite)
mz = np.mean(Prix)

print(mx)
print(my)
print(mz)

# Create a matrix with x,y and z as columns
matrix = np.column_stack((Service, Qualite, Prix))

# Print the matrix
print(matrix)


0.0
1.5
0.0
[[-2  3 -1]
 [-1  1  0]
 [ 2 -1 -1]
 [ 1  3  2]]


In [28]:
#print variance of X1 and X2 and X3
varS=np.var(Service)
varQ=np.var(Qualite)
varP=np.var(Prix)
print(varS)
print(varQ)
print(varP)

2.5
2.75
1.5


In [29]:
#print ecart type of X1 and X2,X3
# Compute the standard deviations
std_x = np.std(Service)
std_y = np.std(Qualite)
std_z = np.std(Prix)

print(std_x)
print(std_y)
print(std_z)

1.5811388300841898
1.6583123951777
1.224744871391589


In [30]:
#Xc which is matrix - (mx,my,mz)
Xc = matrix - np.array([[mx, my,mz]])
print(Xc)

[[-2.   1.5 -1. ]
 [-1.  -0.5  0. ]
 [ 2.  -2.5 -1. ]
 [ 1.   1.5  2. ]]


In [31]:
n = len(matrix)

In [32]:
#Xc transpose
XcT = np.transpose(Xc)
V = 1/n * (XcT@Xc)
V

array([[ 2.5 , -1.5 ,  0.5 ],
       [-1.5 ,  2.75,  1.  ],
       [ 0.5 ,  1.  ,  1.5 ]])

In [33]:
#D matrix diag(1/np.std(x),1/np.std(y))
# Create the diagonal matrix D
D = np.diag(1 / np.std(matrix, axis=0))

print(D)

[[0.63245553 0.         0.        ]
 [0.         0.60302269 0.        ]
 [0.         0.         0.81649658]]


In [34]:
#Xcr = Xc @ D
Xcr = Xc @ D
print(Xcr)

[[-1.26491106  0.90453403 -0.81649658]
 [-0.63245553 -0.30151134  0.        ]
 [ 1.26491106 -1.50755672 -0.81649658]
 [ 0.63245553  0.90453403  1.63299316]]


In [64]:
#Xcr transpose
XcrT = np.transpose(Xcr)
R = 1/n * (XcrT@Xcr)
R

array([[ 1.        , -0.57207755,  0.25819889],
       [-0.57207755,  1.        ,  0.49236596],
       [ 0.25819889,  0.49236596,  1.        ]])

In [74]:
# Calculate eigenvalues and eigenvectors
s, u = np.linalg.eig(R)

indices = np.argsort(s)[::-1]
s = s[indices]
u = u[:, indices]


In [75]:
lambda1 , lambda2,lamda3= s
print(lambda1)
print(lambda2)
print(lamda3)


1.6394490533741495
1.2544638722446844
0.10608707438116793


In [76]:
#les vecteures propres U1,U2,U3 and create matrix U
U1,U2,U3 = u[:,0],u[:,1],u[:,2]
U = np.column_stack((U1,U2,U3))
print(U)


[[-0.53103696  0.63393649  0.5622493 ]
 [ 0.76140143  0.06581093  0.64493161]
 [ 0.37184353  0.77057995 -0.51762818]]


# **Qualite de ACP**

In [77]:
#les cordonnees des individus Xcr@U
individus_cordinate  = Xcr@U
print(individus_cordinate)

[[ 1.05681905 -1.37152095  0.29480887]
 [ 0.10628609 -0.42077938 -0.55005188]
 [-2.12317934  0.07348368  0.16156602]
 [ 0.96007419  1.71881664  0.093677  ]]


In [ ]:
#variance of  Xcr@U is always  = lamda1 and lamda2

In [84]:
#les cordonees des variables: matrixCordinateVariable =  U[:,i] * np.sqrt(lambda i)
matrixCordinateVariable = U * np.sqrt(s)
print(matrixCordinateVariable)

[[-0.67994488  0.71002694  0.18313028]
 [ 0.97490579  0.07371011  0.21006075]
 [ 0.47611208  0.86307151 -0.16859673]]


# quality representation

In [86]:
import numpy as np

# Initialize lists for axe1 and axe2 values
axe1 = []
axe2 = []

# Loop through each individual (i)
for i in range(len(individus_cordinate)):
    # Compute the values for quality_representation_1 and quality_representation_2
    sum_Xcr_squared = Xcr[i][0]**2 + Xcr[i][1]**2 +Xcr[i][2]**2
    quality_representation_1 = (individus_cordinate[i][0]**2) / sum_Xcr_squared
    quality_representation_2 = (individus_cordinate[i][1]**2) / sum_Xcr_squared

    # Append the values for axe1 and axe2
    axe1.append(quality_representation_1)
    axe2.append(quality_representation_2)

# Print the table with axe1 and axe2 values
print("Index | axe1   | axe2")
print("-------------------------")
for i in range(len(axe1)):
    print(f"{i+1:5d} | {axe1[i]:.4f} | {axe2[i]:.4f}")


Index | axe1   | axe2
-------------------------
    1 | 0.3620 | 0.6098
    2 | 0.0230 | 0.3607
    3 | 0.9931 | 0.0012
    4 | 0.2373 | 0.7605


# Contribution a la variance

In [87]:
for i in range(n):

  axe1 = (individus_cordinate[i,0]) **2 / (n* lambda1)
  axe2 = (individus_cordinate[i,1]) **2 / (n* lambda2)
  print(f"axe1 = {axe1}")
  print(f"axe2 = {axe2}")
  print("-------------------------")

axe1 = 0.17031125635323638
axe2 = 0.374875224874432
-------------------------
axe1 = 0.0017226417275587982
axe2 = 0.03528505076758529
-------------------------
axe1 = 0.6874093617699396
axe2 = 0.0010761273852374516
-------------------------
axe1 = 0.1405567401492652
axe2 = 0.5887635969727444
-------------------------


In [88]:
from prettytable import PrettyTable

# Create a PrettyTable object
table = PrettyTable()

# Add columns to the table
table.field_names = ["axe1", "axe2"]

# Add rows to the table
table.add_row([0.17031125635323638, 0.374875224874432])
table.add_row([0.0017226417275587982, 0.03528505076758529])
table.add_row([0.6874093617699396, 0.0010761273852374516])
table.add_row([0.1405567401492652, 0.5887635969727444])

# Set formatting for floating-point numbers
table.float_format = ".6"  # Display up to 6 decimal places

# Print the table
print(table)


+----------+----------+
|   axe1   |   axe2   |
+----------+----------+
| 0.170311 | 0.374875 |
| 0.001723 | 0.035285 |
| 0.687409 | 0.001076 |
| 0.140557 | 0.588764 |
+----------+----------+
